# File       : example.py
# Author     : automatically generated by picker
# Date       : {{date_now}}
# Description: Example usage of {{package_name}} {% if generate_dut %}DUT{% else %}Agent{% endif %}
# Version    : {{version}}

import random
{% if generate_dut -%}
from {{package_name}} import DUT{{package_name}}
{% else -%}
from {{package_name}} import Agent{% for trans in transactions %}, {{trans.name}}{% endfor %}

def create_agent(monitor_callback=None):
    """Create pre-configured agent (transactions auto-registered by default)."""
    return Agent(monitor_callback=monitor_callback)
{% endif %}

if __name__ == "__main__":
    print("="*70)
    print(" {{package_name}} Usage Example ".center(70))
    print("="*70 + "\n")

{% if generate_dut %}
    def monitor_callback(dut):
        """
        Example callback function that gets called after monitor updates.
        This demonstrates how to track and respond to state changes.
        """
        print(f"  [Monitor] Receive from UVM: {dut}")

    # Initialize DUT
    print("Initializing DUT...")
    dut = DUT{{package_name}}()
    dut.InitClock() 
    print("✓ DUT initialized successfully\n")
    
    # Optional: Register callback for monitor updates
    print("Registering monitor callback...")
    dut.SetUpdateCallback(monitor_callback)
    print("✓ Callback registered\n")
    
    for i in range(5):
        # Set field values using clean interface: dut.field.value
        {% for data in variables -%}
        dut.{{data.name}}.value = random.randint(0, (1 << {{data.bit_count}}) - 1)
        {% endfor %}
        
        # Show values before Step
        print(f"  [Driver ] Send to UVM     : {dut}")
        
        # Step advances simulation and syncs with monitor
        dut.Step(1)

{% else %}
    def monitor_handler(trans_type, trans_obj):
        cycle = agent.GetCycleCount()
        print(f"[Monitor] Receive from UVM @ Cycle {cycle} {trans_type}: {trans_obj}")

    # Use factory function for quick setup
    agent = create_agent(monitor_callback=monitor_handler)
    agent.InitClock()

    # Create and drive transactions
    for i in range(5):
        {%- for trans in transactions %}
        tr = {{trans.name}}()
        {% for data in trans.variables %}
        tr.{{data.name}}.value = random.randint(0, (1 << {{data.bit_count}}) - 1)
        {% endfor %}
        cycle = agent.GetCycleCount()
        print(f"[Driver] Send to UVM @ Cycle  {cycle}: {tr}")
        agent.drive(tr)
        agent.run(1)
        {% endfor %}

    agent.run(10)
{% endif %}
