//==============================================================================//
// File       : example_uvm_dut.sv
// Author     : automatically generated by picker
// Date       : {{date_now}}
// Description: UVM testbench for {{package_name}} example
//              Supports bidirectional communication (Python ←→ UVM)
//              - Driver receives transactions from Python
//              - Monitor sends transactions back to Python
// Version    : {{version}}
//==============================================================================//
import uvm_pkg::*;
import uvmc_pkg::*;

// Include common utility package before agents
`include "{{package_name}}/utils_pkg.sv"

// include transaction definitions and agents
{% for trans in transactions -%}
{% if generate_dut -%}
`include "{{trans.filepath}}"
{% else -%}
`include "../{{trans.filepath}}"
{% endif -%}
`include "{{package_name}}/xagent.sv"
{% endfor -%}

interface example_interface(input clk, input rst_n);
    // Add your DUT interface signals here if needed
    // For this example, we just verify that transactions are received
endinterface //example_interface

{% if length(transactions) > 0 -%}
// Multi-transaction mode: create drivers for each transaction type
{% for trans in transactions -%}
class example_{{trans.name}}_driver extends {{trans.name}}_xdriver;
    `uvm_component_utils(example_{{trans.name}}_driver);
    int transaction_count;
    {{trans.name}}_xmonitor mon_handle;
    {% if trans.name == "alu_op" -%}
    // Reference to result monitor for sending ALU results
    alu_result_xmonitor result_mon_handle;
    {% endif -%}
    
    function new (string name = "example_{{trans.name}}_driver", uvm_component parent = null);
        super.new(name,parent);
        transaction_count = 0;
    endfunction

    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
    endfunction

    virtual task sequence_receive({{trans.class_name}} tr);
        transaction_count++;
        `uvm_info("example_{{trans.name}}_driver", $sformatf("Received transaction #%0d from Python:\n%s",
                                               transaction_count, tr.sprint()), UVM_LOW)
        
        {% if trans.name == "alu_op" -%}
        // Process ALU operation and send result
        if (result_mon_handle != null) begin
            alu_result result_trans = alu_result::type_id::create("result_trans");
            
            // Perform ALU operation
            case (tr.opcode)
                2'b00: begin // ADD
                    result_trans.result = tr.operand_a + tr.operand_b;
                    result_trans.status = (result_trans.result > 16'hFFFF) ? 3'b001 : 3'b000; // overflow check
                    result_trans.result = result_trans.result & 16'hFFFF;
                end
                2'b01: begin // SUB
                    if (tr.operand_a >= tr.operand_b) begin
                        result_trans.result = tr.operand_a - tr.operand_b;
                        result_trans.status = 3'b000;
                    end else begin
                        result_trans.result = tr.operand_b - tr.operand_a; // abs value
                        result_trans.status = 3'b100; // negative flag
                    end
                end
                2'b10: begin // MUL
                    result_trans.result = tr.operand_a * tr.operand_b;
                    result_trans.status = (result_trans.result > 16'hFFFF) ? 3'b001 : 3'b000;
                    result_trans.result = result_trans.result & 16'hFFFF;
                end
                2'b11: begin // DIV
                    if (tr.operand_b == 0) begin
                        result_trans.result = 16'h0000;
                        result_trans.status = 3'b001; // overflow (div by zero)
                    end else begin
                        result_trans.result = tr.operand_a / tr.operand_b;
                        result_trans.status = 3'b000;
                    end
                end
            endcase
            
            // Check for zero result
            if (result_trans.result == 0)
                result_trans.status = result_trans.status | 3'b010;
            
            `uvm_info("example_{{trans.name}}_driver", 
                     $sformatf("ALU Result: opcode=%0d, %0d op %0d = %0d, status=0x%0h",
                              tr.opcode, tr.operand_a, tr.operand_b, 
                              result_trans.result, result_trans.status), UVM_LOW)
            
            // Send result back to Python
            result_mon_handle.sequence_send(result_trans);
        end
        
        // Echo input back via monitor
        if (mon_handle != null) begin
            mon_handle.sequence_send(tr);
        end
        {% else -%}
        // Echo back the received transaction to Python via monitor
        if (mon_handle != null) begin
            mon_handle.sequence_send(tr);
        end
        {% endif -%}
    endtask
    
    function void report_phase(uvm_phase phase);
        super.report_phase(phase);
        `uvm_info("example_{{trans.name}}_driver", $sformatf("Total transactions received: %0d", transaction_count), UVM_LOW)
    endfunction
endclass

{% endfor -%}
{% else -%}
// Single transaction mode
class example_driver extends {{package_name}}_xdriver;
    `uvm_component_utils(example_driver);
    int transaction_count;
    
    function new (string name = "example_driver", uvm_component parent = null);
        super.new(name,parent);
        transaction_count = 0;
    endfunction

    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
    endfunction

    virtual task sequence_receive({{trans_class_name}} tr);
        transaction_count++;
        `uvm_info("example_driver", $sformatf("Received transaction #%0d from Python:\n%s",
                                               transaction_count, tr.sprint()), UVM_LOW)
        
        // Echo back the received transaction to Python via monitor
        if (mon_handle != null) begin
            mon_handle.sequence_send(tr);
        end
    endtask
    
    function void report_phase(uvm_phase phase);
        super.report_phase(phase);
        `uvm_info("example_driver", $sformatf("Total transactions received: %0d", transaction_count), UVM_LOW)
    endfunction
endclass
{% endif -%}


class example_env extends uvm_env;
    `uvm_component_utils(example_env)
    {% if length(transactions) > 0 -%}
    // Multi-transaction mode: one agent per transaction type
    {% for trans in transactions -%}
    {{trans.name}}_xagent            {{trans.name}}_agent;
    {{trans.name}}_xagent_config     {{trans.name}}_config;
    example_{{trans.name}}_driver    {{trans.name}}_drv;
    {% endfor -%}
    {% else -%}
    // Single transaction mode
    {{package_name}}_xagent            xagent;
    {{package_name}}_xagent_config     xagent_config;
    example_driver                  drv;
    {% endif -%}
    virtual example_interface       vif;
    
    function new (string name = "example_env", uvm_component parent = null);
        super.new(name,parent);
        {% if length(transactions) > 0 -%}
        // Multi-transaction configs - use factory override for custom driver types
        {% for trans in transactions -%}
        {{trans.name}}_config = new("{{trans.name}}_config");
        // Set to UVM_ACTIVE for both monitor and driver (default behavior)
        {{trans.name}}_config.is_active = UVM_ACTIVE;
        uvm_config_db#({{trans.name}}_xagent_config)::set(this,"{{trans.name}}_agent", "{{trans.name}}_xagent_config", {{trans.name}}_config);

        // Use factory override to replace default driver with example driver
        set_type_override_by_type({{trans.name}}_xdriver::get_type(), example_{{trans.name}}_driver::get_type());
        {% endfor -%}
        {% else -%}
        // Single transaction config - use factory override for custom driver type
        xagent_config = new("xagent_config");
        // Set to UVM_ACTIVE for both monitor and driver (default behavior)
        xagent_config.is_active = UVM_ACTIVE;
        uvm_config_db#({{package_name}}_xagent_config)::set(this,"xagent", "{{package_name}}_xagent_config", xagent_config);

        // Use factory override to replace default driver with example driver
        set_type_override_by_type({{package_name}}_xdriver::get_type(), example_driver::get_type());
        {% endif -%}
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        {% if length(transactions) > 0 -%}
        // Build multi-transaction agents
        {% for trans in transactions -%}
        {{trans.name}}_agent = {{trans.name}}_xagent::type_id::create("{{trans.name}}_agent",this);
        {% endfor -%}
        {% else -%}
        // Build single agent
        xagent = {{package_name}}_xagent::type_id::create("xagent",this);
        {% endif -%}
        if(!uvm_config_db#(virtual example_interface)::get(this,"","vif",vif))
            `uvm_fatal("example_env","virtual interface must be set for vif")
    endfunction
    
    function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);
        {% if length(transactions) > 0 -%}
        // Connect drivers to monitors for echo back (multi-transaction)
        {% for trans in transactions -%}
        if ({{trans.name}}_agent.{{trans.name}}_xdrv != null && {{trans.name}}_agent.{{trans.name}}_xmon != null) begin
            if ($cast({{trans.name}}_drv, {{trans.name}}_agent.{{trans.name}}_xdrv)) begin
                {{trans.name}}_drv.mon_handle = {{trans.name}}_agent.{{trans.name}}_xmon;
            end
        end
        {% endfor -%}

        {% else -%}
        // Connect driver to monitor for echo back (single transaction)
        if (xagent.{{package_name}}_xdrv != null && xagent.{{package_name}}_xmon != null) begin
            if ($cast(drv, xagent.{{package_name}}_xdrv)) begin
                drv.mon_handle = xagent.{{package_name}}_xmon;
            end
        end
        {% endif -%}
    endfunction

    virtual task main_phase(uvm_phase phase);
        phase.raise_objection(this);
        // Just wait for Python to send transactions
        // Python controls the simulation time via Step() calls
        #10000;  // Wait long enough for Python to complete
        phase.drop_objection(this);
    endtask

endclass


class example_test extends uvm_test;
    `uvm_component_utils(example_test)
    example_env env;
    
    function new (string name = "example_test", uvm_component parent = null);
        super.new(name,parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        env = example_env::type_id::create("example_env",this);
    endfunction
endclass


module sv_main;
    logic clk;
    logic rst_n;
    example_interface vif(clk,rst_n);
    
    initial begin
        clk = 0;
        forever begin
            #2
            clk <= ~clk;
        end
    end
    
    initial begin
        rst_n <= 1'b0;
        #10
        rst_n <= 1'b1;
    end
    
    initial begin
        uvm_config_db #(virtual example_interface)::set(null,"uvm_test_top.example_env","vif",vif);
        run_test("example_test");
    end
endmodule
