# File       : example_uvm.sv
# Author     : automatically generated by picker
# Date       : {{datenow}}
# Description: This is an example of using the picker with Python. 
#              In this example, python sub the msg from UVM and parse it to object,then
#              pub the object to UVM
# Version    : {{version}}

import sys
sys.path.append('../')
from {{className}}_xagent import *


if __name__ == "__main__":
    
    def receive_sequence(message):
        """
        handle received sequence from UVM
        this function only send it to UVM, you can customize this function according to your needs
        """

        sequence = {{className}}(message)
        print("python receive sequence",{%for data in variables -%} sequence.{{data.name}}.value{%if not loop.is_last -%}, {%endif -%}{%endfor -%})
        sequence.send(agent)

    agent = Agent("{{className}}","{{className}}",receive_sequence)
    
    agent.run(500)
