//==============================================================================
// File       : {{ class_name }}.sv
// Author     : automatically generated by picker from RTL
// Date       : {{ date_now }}
// Description: Transaction for {{ class_name }} DUT
// Version    : {{ version }}
//==============================================================================

class {{ class_name }} extends uvm_sequence_item;
{% for data in variables -%}
    rand bit{% if data.bit_count > 1 %} [{{ data.bit_count - 1 }}:0]{% endif %} {{ data.name }};  // auto-generated from RTL port
{% endfor %}
    `uvm_object_utils_begin({{ class_name }})
{% for data in variables -%}
        `uvm_field_int({{ data.name }}, UVM_ALL_ON)
{% endfor -%}
    `uvm_object_utils_end

    function new(string name = "{{ class_name }}");
        super.new(name);
    endfunction
endclass
