//==============================================================================
// File       : picker_uvm_utils_pkg.sv
// Author     : automatically generated by picker
// Description: Common utility package for UVM-Python communication
//              Provides shared serialization/deserialization functions
// Version    : 1.0
//==============================================================================

package utils_pkg;

    // Maximum field width supported for serialization
    parameter int MAX_FIELD_WIDTH = 2048;

    // TLM timing constants
    parameter real TIME_UNIT = 1e-12;
    parameter real TRANSPORT_DELAY = 1e-9;

   `define PICKER_UNPACK_STREAM(VAR, OFFSET, BIT_COUNT) \
       begin \
           bit [BIT_COUNT-1:0] picker_tmp_exact; \
           bit [((BIT_COUNT + 7) / 8) * 8 - 1:0] picker_tmp_unpack; \
           {>>{picker_tmp_unpack}} = m_transport_data[OFFSET +: (BIT_COUNT + 7) / 8]; \
           picker_tmp_exact = picker_tmp_unpack[((BIT_COUNT + 7) / 8) * 8 - 1 -: BIT_COUNT]; \
           {>>{VAR}} = picker_tmp_exact; \
       end

   `define PICKER_UNPACK_BYTE(VAR, OFFSET) \
       VAR = m_transport_data[OFFSET]

   `define PICKER_PACK_STREAM(VAR, OFFSET, BIT_COUNT) \
       begin \
           bit [BIT_COUNT-1:0] picker_tmp_exact; \
           bit [((BIT_COUNT + 7) / 8) * 8 - 1:0] picker_tmp_pack; \
           {>>{picker_tmp_exact}} = VAR; \
           picker_tmp_pack = {picker_tmp_exact, {((((BIT_COUNT + 7) / 8) * 8) - BIT_COUNT){1'b0}}}; \
           {>>{m_transport_data[OFFSET +: (BIT_COUNT + 7) / 8]}} = picker_tmp_pack; \
       end

   `define PICKER_PACK_BYTE(VAR, OFFSET) \
      m_transport_data[OFFSET] = VAR

endpackage : utils_pkg
