//==============================================================================
// File       : picker_uvm_utils_pkg.sv
// Author     : automatically generated by picker
// Description: Common utility package for UVM-Python communication
//              Provides shared serialization/deserialization functions
// Version    : 1.0
//==============================================================================

package utils_pkg;

    // Maximum field width supported for serialization
    parameter int MAX_FIELD_WIDTH = 2048;

    // TLM timing constants
    parameter real TIME_UNIT = 1e-12;
    parameter real TRANSPORT_DELAY = 1e-9;

   `define PICKER_UNPACK_STREAM(VAR, OFFSET, BIT_COUNT) \
       {>>{VAR}} = m_transport_data[OFFSET +: (BIT_COUNT +7) / 8]

   `define PICKER_UNPACK_BYTE(VAR, OFFSET) \
       VAR = m_transport_data[OFFSET]

   `define PICKER_PACK_STREAM(VAR, OFFSET, BIT_COUNT) \
       {>>{m_transport_data[OFFSET +: (BIT_COUNT + 7) / 8]}} = VAR

   `define PICKER_PACK_BYTE(VAR, OFFSET) \
      m_transport_data[OFFSET] = VAR

endpackage : utils_pkg
