name: Basic Env Docker Build and Publish

on:
  push:
    # master or any *appimage* branch
    branches:
      - master
      - '*appimage*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm64]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize AppImage environment
        run: |
          ARCH=$(uname -m)
          if [ "$ARCH" = "arm64" ]; then
            ARCH="aarch64"
          fi
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-${ARCH}.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${ARCH}.AppImage
          chmod +x appimagetool-${ARCH}.AppImage
          sudo mv appimagetool-${ARCH}.AppImage /usr/bin/appimagetool
          chmod +x linuxdeploy-${ARCH}.AppImage
          sudo mv linuxdeploy-${ARCH}.AppImage /usr/bin/linuxdeploy
      
      - name: Build AppImage
        run: |
          # Build the AppImage
          make appimage

      - name: Upload AppImage for next jobs
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-appimage
          path: '*.AppImage'

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    # Only run this job for pushes to master or any branch starting with 'appimage'
    if: |
      contains(github.ref, 'appimage') || contains(github.ref, 'master')
    steps:

      - name: Download AppImage
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: appimages

      - name: Create AppImage release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            appimages/*.AppImage
          tag_name: ${{ github.sha }}
          release_name: Picker AppImage ${{ github.sha }}
          body: |
            This is the AppImage release for Picker.
            It includes the latest changes and features.
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}